name: Test ansible role installation and publish to galaxy
on:
  push:
    branches:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
         path: "ansible-role-sysmon"
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: "ansible-role-sysmon"

  test:
    needs: lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "ansible-role-sysmon"
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel git gcc msys2-devel python3 python3-pip libffi libffi-devel libcrypt libcrypt-devel openssl openssl-devel
      - name: Download ConfigureRemotingForAnsible.ps1
        run: wget https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -Outfile ConfigureRemotingForAnsible.ps1
        shell: powershell
      - name: Run ConfigureRemotingForAnsible.ps1
        run: .\ConfigureRemotingForAnsible.ps1 -Verbose -GlobalHttpFirewallAccess -ForceNewSSLCert
        shell: powershell
      - name: Prepare Administrator user
        run: |
          $password = ConvertTo-SecureString "Password123" -AsPlainText -Force
          New-LocalUser "Ansible" -Password $password -Description "Ansible remoting user"
          Add-LocalGroupMember -Group Administrators -Member Ansible
          Enable-LocalUser -Name "Ansible"
        shell: powershell
      - name: Install Ansible
        shell: msys2 {0}
        run: CFLAGS=-I/usr/lib/libffi-3.2.1/include python -m pip install ansible pywinrm
      - name: Run Ansible playbook
        shell: msys2 {0}
        run: |
          ansible-playbook -i ansible-role-sysmon/.github/scripts/inventory ansible-role-sysmon/.github/scripts/playbook.yml
      - name: Run test script
        run: .\ansible-role-sysmon\.github\scripts\sysmon_test.ps1
        shell: powershell
       
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish on Ansible Galaxy
        uses: robertdebock/galaxy-action@1.0.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
